### ISSUE TITLE
Sort order doesn't work

### ISSUE THREAD

**Issue by melvingrootenboers** [mendix/SimpleCheckboxSetSelector#1]
Steps to reproduce:
1. Set Data source type to XPath
2. Select a Datasource Entity
3. Set Sort order to Ascending
4. Select Sort attribute (select an attribute with type String)

Result:
Options not shown in alphabetical order
![image](https://cloud.githubusercontent.com/assets/10810429/12418747/6ce929ba-beb1-11e5-83db-cbdc116e14bd.png)

**Comment by JelteMX** [comment]
After reviewing the code and test-project, we cannot reproduce this behaviour.
